name: freelpay-nextjs
services:
  - name: mongodb
    image: mongo:latest
    http_port: 27017
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_DISABLE_LOGGING
        value: "true"
    volumes:
      - name: mongodb_data
        mount_path: /data/db

  - name: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: MONGODB_DB_NAME
        value: ${MONGODB_DB_NAME}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
    depends_on:
      - mongodb

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  - name: mongodb_data