name: freelpay-nextjs
services:
  - name: backend
    source_dir: backend
    github:
      branch: main
      deploy_on_push: false
      repo: IllanKnf/freelpay-nextjs
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: MONGO_DB_NAME
        value: ${MONGO_DB_NAME}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
      - key: SUPABASE_DB_NAME
        value: ${SUPABASE_DB_NAME}
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
      - key: SUPABASE_SERVICE_KEY
        value: ${SUPABASE_SERVICE_KEY}
      - key: SUPABASE_POSTGRES_URI
        value: ${SUPABASE_POSTGRES_URI}
      - key: SIREN_API_KEY
        value: ${SIREN_API_KEY}
      - key: PENNYLANE_API_KEY
        value: ${PENNYLANE_API_KEY}
      - key: PANDADOC_API_KEY
        value: ${PANDADOC_API_KEY}
   
  - name: frontend
    source_dir: frontend
    github:
      branch: main
      deploy_on_push: false
      repo: IllanKnf/freelpay-nextjs
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${NEXT_PUBLIC_API_URL}
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}